name: "GarageHQ S3 Server"
version: "1.0.0"
slug: "garagehq"
description: "S3-compatible storage server for Home Assistant"
url: "https://github.com/home-assistant/addons/tree/master/garagehq"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
init: false
map:
  - share:rw
  - addon_config:rw
ports:
  9000/tcp: 9000
  3902/tcp: 3902
ports_description:
  9000/tcp: "S3 API port"
  3902/tcp: "Web interface port (optional)"
options:
  storage_path: "/share/garagehq"
  access_key: ""
  secret_key: ""
  region: "us-east-1"
  replication_factor: 1
  web_ui_enabled: true
  advanced_options: false
  log_level: "info"
  snapshot_interval: "24h"
schema:
  storage_path: "str"
  access_key: "str"
  secret_key: "password"
  region: "str"
  replication_factor: "int(1,3)"
  web_ui_enabled: "bool"
  advanced_options: "bool"
  log_level: "list(error|warn|info|debug|trace)"
  rpc_secret: "password?"
  metadata_dir: "str?"
  data_dir: "str?"
  snapshot_interval: "str?"
